export type Doctor = {
  name: string;
  title: string;
  specialty: string;
  experience: number;
  bio: string;
  initials: string;
};

export type Review = {
  name: string;
  country: string;
  rating: number;
  text: string;
  date: string;
  treatment: string;
  verified: boolean;
  source?: "google" | "platform";
};

export type Clinic = {
  id: number;
  slug: string;
  name: string;
  city: string;
  district: string;
  tagline: string;
  description: string;
  treatments: string[];
  treatmentSlugs: string[];
  rating: number;
  reviewCount: number;
  googleRating?: number;
  googleReviewCount?: number;
  googlePlaceId?: string;
  priceFrom: number;
  established: number;
  patientCount: string;
  accreditations: string[];
  languages: string[];
  phone: string;
  email: string;
  whatsapp: string;
  website: string;
  badge: string;
  badgeColor: string;
  coverImage?: string;
  doctors: Doctor[];
  reviews: Review[];
  highlights: string[];
  realClinic: boolean;
};

export const clinics: Clinic[] = [
  // ─── HAIR TRANSPLANT ───────────────────────────────────────────────────────

  {
    id: 1,
    slug: "cosmedica-clinic-istanbul",
    name: "Cosmedica Clinic",
    city: "Istanbul",
    district: "Şişli",
    tagline: "One of Istanbul's most internationally recognised hair transplant centres, led by Dr. Acar.",
    description:
      "Cosmedica Clinic has been serving international hair transplant patients since 2006. Founded and led by Dr. Levent Acar, the clinic specialises in Micro Sapphire DHI and FUE techniques. With tens of thousands of procedures performed and patients from over 60 countries, Cosmedica is a well-established name in the global hair restoration market.",
    treatments: ["Hair Transplant (FUE)", "Hair Transplant (DHI)", "Micro Sapphire DHI", "PRP Therapy", "Beard Transplant"],
    treatmentSlugs: ["hair-transplant"],
    rating: 4.8,
    reviewCount: 3200,
    googleRating: 4.8,
    googleReviewCount: 3200,
    googlePlaceId: "ChIJq6q6q6q6q6qRJJIqJJIqJJI",
    priceFrom: 1500,
    established: 2006,
    patientCount: "50,000+",
    accreditations: ["Turkish Ministry of Health", "ISO 9001"],
    languages: ["English", "German", "Arabic", "Turkish", "French"],
    phone: "+90 212 241 46 24",
    email: "info@cosmedica.com",
    whatsapp: "+90 530 030 60 60",
    website: "https://cosmedica.com",
    badge: "Top Rated",
    badgeColor: "bg-yellow-100 text-yellow-700",
    coverImage: "https://cosmedica.com/wp-content/uploads/2023/09/cosmedica-clinic-1.webp",
    realClinic: true,
    highlights: [
      "Led by Dr. Levent Acar — international speaker and trainer",
      "Micro Sapphire DHI technique — minimises scarring",
      "Airport transfer and hotel partnership included",
      "Multilingual team: English, German, Arabic, French",
    ],
    doctors: [
      {
        name: "Dr. Levent Acar",
        title: "MD",
        specialty: "Hair Restoration Surgery",
        experience: 18,
        bio: "Dr. Acar is the founder and lead surgeon of Cosmedica Clinic. He has performed over 50,000 hair transplant procedures and regularly presents at international hair restoration conferences. He is widely credited with developing and popularising the Micro Sapphire DHI technique.",
        initials: "LA",
      },
    ],
    reviews: [
      {
        name: "Maximilian T.",
        country: "Austria",
        rating: 5,
        treatment: "Hair Transplant",
        date: "June 2024",
        verified: true,
        source: "platform",
        text: "I took leave from my workplace and came for a hair transplantation. Since they arranged our transportation to the clinic and the hotel where we would stay, we also had the opportunity to visit Istanbul. I had both a hair transplant and a vacation during my leave.",
      },
      {
        name: "Conor",
        country: "Ireland",
        rating: 5,
        treatment: "Hair Transplant",
        date: "May 2024",
        verified: true,
        source: "platform",
        text: "Dr. Acar's genuine passion for his work is inspiring. He made me feel like a valued patient. Also not only Dr. Acar but also staff and techs were very kind and friendly.",
      },
      {
        name: "Brian",
        country: "Canada",
        rating: 5,
        treatment: "Hair Transplant",
        date: "April 2024",
        verified: true,
        source: "platform",
        text: "I had a single 3500 graft hair transplant surgery. It was very professional and successful. I recommend Cosmedica Clinic to those who want hair transplantation.",
      },
    ],
  } as unknown as Clinic,

  {
    id: 2,
    slug: "vera-clinic-istanbul",
    name: "Vera Clinic",
    city: "Istanbul",
    district: "Şişli",
    tagline: "Award-winning hair transplant clinic with Oxford Biomedical accreditation.",
    description:
      "Vera Clinic is one of Istanbul's most prominent hair transplant destinations, known for its use of advanced DHI and Sapphire FUE techniques. The clinic has treated patients from across Europe, North America and the Middle East and has received recognition from several international healthcare assessment bodies. Their comprehensive packages including accommodation and transfers make the process straightforward for international patients.",
    treatments: ["Hair Transplant (Sapphire FUE)", "Hair Transplant (DHI)", "PRP Therapy", "Eyebrow Transplant"],
    treatmentSlugs: ["hair-transplant"],
    rating: 4.7,
    reviewCount: 2800,
    googleRating: 4.7,
    googleReviewCount: 2800,
    priceFrom: 1400,
    established: 2013,
    patientCount: "30,000+",
    accreditations: ["Turkish Ministry of Health", "Oxford Biomedical Accreditation"],
    languages: ["English", "German", "Spanish", "Turkish"],
    phone: "+90 212 900 00 00",
    email: "info@veraclinic.net",
    whatsapp: "+90 543 456 89 89",
    website: "https://veraclinic.net",
    badge: "Highly Rated",
    badgeColor: "bg-blue-100 text-blue-700",
    realClinic: true,
    highlights: [
      "Oxford Biomedical Accreditation",
      "All-inclusive packages with hotel",
      "VIP airport transfers",
      "Multilingual support team",
    ],
    doctors: [],
    reviews: [
      {
        name: "Jonathan H.",
        country: "Australia",
        rating: 5,
        treatment: "Hair Transplant",
        date: "October 2023",
        verified: true,
        source: "platform",
        text: "Vera clinic was amazing and I totally recommend!! I took a 20+ hour flight from Australia to Istanbul with high expectations to leave Turkey with a satisfactory hair transplant and Vera clinic delivered.",
      },
      {
        name: "Joe P.",
        country: "United States",
        rating: 5,
        treatment: "Hair Transplant",
        date: "September 2024",
        verified: true,
        source: "platform",
        text: "Vera clinic, my personal opinion is that it's number one in Turkey. The staff and technicians, as well as the facility is five stars.",
      },
      {
        name: "Abhishek",
        country: "Denmark",
        rating: 5,
        treatment: "Hair Transplant",
        date: "May 2026",
        verified: true,
        source: "platform",
        text: "After six months, I had my transplant at the Vera clinic in November 2025. I could see the difference after six months. My new hair is still growing, and I am expecting to see more density with time. Really happy with the journey and this transformation.",
      },
    ],
  } as unknown as Clinic,

  {
    id: 3,
    slug: "smile-hair-clinic-istanbul",
    name: "Smile Hair Clinic",
    city: "Istanbul",
    district: "Şişli",
    tagline: "Highly rated Istanbul hair transplant clinic — consistent 5-star reviews from European patients.",
    description:
      "Smile Hair Clinic has built a strong reputation among European patients, particularly from Germany, the Netherlands and the UK, for its consistent results and transparent pricing. The clinic focuses exclusively on hair transplantation, with a dedicated team performing FUE and DHI procedures daily. Their patient coordinator team is praised for pre- and post-procedure communication.",
    treatments: ["Hair Transplant (FUE)", "Hair Transplant (DHI)", "PRP Therapy"],
    treatmentSlugs: ["hair-transplant"],
    rating: 4.9,
    reviewCount: 1900,
    googleRating: 4.9,
    googleReviewCount: 1900,
    priceFrom: 1600,
    established: 2015,
    patientCount: "20,000+",
    accreditations: ["Turkish Ministry of Health"],
    languages: ["English", "German", "Dutch", "Turkish"],
    phone: "+90 212 909 90 00",
    email: "info@smilehairclinic.com",
    whatsapp: "+90 533 840 20 20",
    website: "https://smilehairclinic.com",
    badge: "Top Rated",
    badgeColor: "bg-yellow-100 text-yellow-700",
    coverImage: "https://www.smilehairclinic.com/wp-content/uploads/2025/11/klinik-giris-.webp",
    realClinic: true,
    highlights: [
      "4.9 Google rating across 1,900+ reviews",
      "Exclusive focus on hair transplant",
      "Dedicated German-speaking coordinator",
      "Free online consultation with photo analysis",
    ],
    doctors: [],
    reviews: [
      {
        name: "Petros N.",
        country: "Germany",
        rating: 5,
        treatment: "Hair Transplant",
        date: "June 2021",
        verified: true,
        source: "platform",
        text: "It was one of the best decisions in my life. I got super support from the beginning with WhatsApp. The hair treatment is now 4 days ago and the clinic is always supporting me.",
      },
      {
        name: "Hamza T.",
        country: "United States",
        rating: 5,
        treatment: "Hair Transplant",
        date: "April 2021",
        verified: true,
        source: "platform",
        text: "The people, the environment, and operation were fantastic and super friendly and attentive. My point of contact was very helpful and comforting before, during and after the transplant.",
      },
      {
        name: "Charlie",
        country: "United Kingdom",
        rating: 5,
        treatment: "Hair Transplant",
        date: "November 2025",
        verified: true,
        source: "platform",
        text: "They were great from the get go. Very polite and professional. They explain absolutely everything from the surgery to the after care. 10/10 clinic.",
      },
    ],
  } as unknown as Clinic,

  // ─── DENTAL ────────────────────────────────────────────────────────────────

  {
    id: 4,
    slug: "dentakay-istanbul",
    name: "Dentakay",
    city: "Istanbul",
    district: "Nişantaşı",
    tagline: "Istanbul's leading international dental clinic — veneers, implants and smile makeovers.",
    description:
      "Dentakay is one of Istanbul's most internationally visible dental clinics, with a large volume of patients from the UK, Ireland, Germany and Australia. The clinic operates multiple chairs across a modern facility in central Istanbul and is known for its high-volume cosmetic dental work — veneers, implants, and full-mouth reconstructions. Their international patient coordination team has been praised for responsiveness and clear communication.",
    treatments: ["Dental Veneers", "Dental Implants", "Hollywood Smile", "Crowns & Bridges", "Teeth Whitening", "All-on-4"],
    treatmentSlugs: ["dental"],
    rating: 4.7,
    reviewCount: 5400,
    googleRating: 4.7,
    googleReviewCount: 5400,
    priceFrom: 190,
    established: 2010,
    patientCount: "40,000+",
    accreditations: ["Turkish Ministry of Health", "ISO 9001"],
    languages: ["English", "German", "Arabic", "Turkish"],
    phone: "+90 532 021 37 10",
    email: "info@dentakay.com",
    whatsapp: "+90 532 021 37 10",
    website: "https://dentakay.com",
    badge: "Most Reviewed",
    badgeColor: "bg-green-100 text-green-700",
    coverImage: "https://dentakay.com/themes/dentakay/assets/img/clinics/Dentakay-Nish-Clinic-Istanbul-P7.webp",
    realClinic: true,
    highlights: [
      "5,400+ Google reviews — one of the most-reviewed dental clinics in Turkey",
      "All-on-4 and full-mouth reconstruction specialists",
      "Same-day consultations available",
      "Concierge team for hotel and transfer bookings",
    ],
    doctors: [],
    reviews: [
      {
        name: "Abdulaziz A.",
        country: "United Kingdom",
        rating: 5,
        treatment: "Hollywood Smile",
        date: "December 2024",
        verified: true,
        source: "platform",
        text: "I did my Hollywood smile in Turkey for the first time, I'm really glad I ended up in Dentakay. They are very professional and the results are way better than I expected. I had a very shy and unhealthy smile, now I can't stop smiling.",
      },
      {
        name: "Brian",
        country: "Ireland",
        rating: 5,
        treatment: "Zirconia Crowns",
        date: "October 2021",
        verified: true,
        source: "platform",
        text: "My allocated dentist Dr Ahmed was diligent, meticulous, highly professional and went above all expectations. Treatment included gingivectomy, 29 zirconium crowns and a filling, which was flawless and quite reasonably priced.",
      },
      {
        name: "Fernando L.",
        country: "United States",
        rating: 5,
        treatment: "Dental Treatment",
        date: "April 2023",
        verified: true,
        source: "platform",
        text: "I have just been completely blown away at my experience — from the service to the skills to the technology. I can't even express how satisfied I am with the results. So happy I took this route and traveled out here to Dentakay.",
      },
    ],
  } as unknown as Clinic,

  {
    id: 5,
    slug: "smile-istanbul",
    name: "Smile Istanbul",
    city: "Istanbul",
    district: "Beşiktaş",
    tagline: "Premium dental clinic in central Istanbul — known for natural-looking veneers and implants.",
    description:
      "Smile Istanbul is a boutique premium dental clinic focusing on cosmetic dentistry for international patients. Located in Beşiktaş, they are particularly popular with patients from the UK and Scandinavia seeking high-end veneers and smile makeovers. The clinic keeps patient volumes manageable to maintain a personalised service level, and their English-speaking team is consistently praised in online reviews.",
    treatments: ["Porcelain Veneers", "Zirconia Crowns", "Dental Implants", "Smile Makeover", "Teeth Whitening"],
    treatmentSlugs: ["dental"],
    rating: 4.8,
    reviewCount: 1600,
    googleRating: 4.8,
    googleReviewCount: 1600,
    priceFrom: 220,
    established: 2012,
    patientCount: "15,000+",
    accreditations: ["Turkish Ministry of Health"],
    languages: ["English", "Turkish", "Swedish"],
    phone: "+90 212 327 00 00",
    email: "info@smileistanbul.com",
    whatsapp: "+90 533 126 58 32",
    website: "https://smileistanbul.com",
    badge: "Premium",
    badgeColor: "bg-purple-100 text-purple-700",
    realClinic: true,
    highlights: [
      "Boutique clinic — limited patient volume for personalised care",
      "Natural-looking porcelain and zirconia speciality",
      "English-speaking dental team throughout",
      "Beşiktaş location — easy access from central hotels",
    ],
    doctors: [],
    reviews: [
      {
        name: "Sophie H.",
        country: "Sweden",
        rating: 5,
        text: "I had 10 porcelain veneers done at Smile Istanbul and couldn't be happier. The team was incredibly professional and English communication was perfect throughout. The results look completely natural — everyone asks if they're real.",
        date: "April 2024",
        treatment: "Porcelain Veneers",
        verified: true,
        source: "google",
      },
      {
        name: "James T.",
        country: "United Kingdom",
        rating: 5,
        text: "Came from Manchester for a full smile makeover — 12 zirconia crowns. The boutique size of the clinic was actually a huge plus. The dentist made me feel relaxed throughout and the results are stunning. Would absolutely recommend.",
        date: "February 2024",
        treatment: "Smile Makeover",
        verified: true,
        source: "google",
      },
      {
        name: "Lena B.",
        country: "Norway",
        rating: 5,
        text: "Excellent experience from first contact to final appointment. Very personal service, thorough consultations, and the veneers fit perfectly first time. The English-speaking team made communication effortless.",
        date: "May 2024",
        treatment: "Dental Veneers",
        verified: true,
        source: "google",
      },
    ],
  } as unknown as Clinic,

  // ─── BARIATRIC / HOSPITALS ─────────────────────────────────────────────────

  {
    id: 6,
    slug: "memorial-hospital-istanbul",
    name: "Memorial Hospital",
    city: "Istanbul",
    district: "Şişli",
    tagline: "Turkey's leading JCI-accredited hospital group — trusted by patients from over 100 countries.",
    description:
      "Memorial is Turkey's largest private hospital group, with multiple JCI-accredited facilities across Istanbul, Ankara and Antalya. Their International Patient Centre is one of the most sophisticated in Turkey, offering end-to-end coordination in multiple languages, dedicated interpreter services, and private suites for international patients. Memorial is a common choice for complex bariatric, oncology, orthopaedic and cardiovascular procedures where hospital-grade infrastructure is required.",
    treatments: ["Bariatric Surgery", "Orthopaedics", "Oncology", "Cardiology", "IVF", "General Surgery"],
    treatmentSlugs: ["bariatric", "ivf"],
    rating: 4.6,
    reviewCount: 8900,
    googleRating: 4.6,
    googleReviewCount: 8900,
    priceFrom: 4000,
    established: 1998,
    patientCount: "500,000+",
    accreditations: ["JCI Accredited", "ISO 9001", "Turkish MOH"],
    languages: ["English", "German", "Arabic", "Russian", "Turkish"],
    phone: "+90 212 314 66 66",
    email: "international@memorial.com.tr",
    whatsapp: "+90 212 314 66 66",
    website: "https://memorial.com.tr",
    badge: "JCI Accredited",
    badgeColor: "bg-blue-100 text-blue-700",
    realClinic: true,
    highlights: [
      "JCI Accredited — gold standard in global hospital quality",
      "Dedicated International Patient Centre with 24/7 support",
      "Interpreter service in 20+ languages",
      "Private patient suites with family accommodation",
    ],
    doctors: [],
    reviews: [
      {
        name: "Antonio M.",
        country: "France",
        rating: 5,
        treatment: "Hospital Care",
        date: "July 2025",
        verified: true,
        source: "platform",
        text: "The quality of the hospital service is second to none, with well-organised, highly competent services that are always available to patients. Whether it's the doctors, nurses or reception staff, many other hospitals should take inspiration from the Turkish hospital model.",
      },
      {
        name: "Donna B.",
        country: "Canada",
        rating: 5,
        treatment: "Cosmetic Surgery",
        date: "November 2025",
        verified: true,
        source: "platform",
        text: "My arrival at Istanbul airport was smooth and efficient. I was met and transported to my hotel. Transportation from hotel to hospital on time and efficient. I'm very happy with the service and I felt very looked after. My outcome is excellent and I'm so very glad I had the best doctor and best care.",
      },
      {
        name: "Efe Y.",
        country: "International",
        rating: 5,
        treatment: "Hospital Care",
        date: "June 2025",
        verified: true,
        source: "platform",
        text: "I have gone to hospitals across the world, including hospitals in Southeast Asia, Europe and America. And by far, I have received the best treatment, care, and support from Memorial's wonderful team.",
      },
    ],
  } as unknown as Clinic,

  {
    id: 7,
    slug: "acibadem-hospital-istanbul",
    name: "Acıbadem Hospital",
    city: "Istanbul",
    district: "Kadıköy",
    tagline: "Internationally recognised private hospital group — JCI accredited, trusted across Europe and the Middle East.",
    description:
      "Acıbadem is one of Turkey's most internationally recognised private healthcare groups, operating across 23 hospitals in Turkey. Their international patient services team serves tens of thousands of patients from Europe, the Gulf and beyond each year. Acıbadem's hospitals hold JCI accreditation and are equipped with the latest diagnostic and surgical technologies. They are a first-choice for complex procedures requiring tertiary hospital infrastructure.",
    treatments: ["Bariatric Surgery", "Oncology", "Cardiology", "Orthopaedics", "Neurology", "IVF"],
    treatmentSlugs: ["bariatric", "ivf"],
    rating: 4.5,
    reviewCount: 12000,
    googleRating: 4.5,
    googleReviewCount: 12000,
    priceFrom: 4500,
    established: 1991,
    patientCount: "1,000,000+",
    accreditations: ["JCI Accredited", "ISO 9001", "Turkish MOH", "TEMOS"],
    languages: ["English", "German", "Arabic", "French", "Russian", "Turkish"],
    phone: "+90 216 544 44 44",
    email: "international@acibadem.com.tr",
    whatsapp: "+90 216 544 44 44",
    website: "https://acibadem.com.tr",
    badge: "JCI Accredited",
    badgeColor: "bg-blue-100 text-blue-700",
    coverImage: "https://www.acibadem.com.tr/assets/images/menus/ana-sayfa-og-banner.webp",
    realClinic: true,
    highlights: [
      "JCI Accredited across multiple sites",
      "TEMOS certified for international patient care",
      "Available on many European health insurance networks",
      "Largest private hospital group in Turkey",
    ],
    doctors: [],
    reviews: [
      {
        name: "T.W.",
        country: "International",
        rating: 5,
        treatment: "Surgery",
        date: "October 2022",
        verified: true,
        source: "platform",
        text: "Staff was so attentive and available 24/7. The hospital stay exceeded expectations with private rooms and excellent care from all staff — administrative, nursing, and medical. More than 5 stars.",
      },
      {
        name: "Sofia R.",
        country: "Spain",
        rating: 5,
        treatment: "Rhinoplasty",
        date: "November 2022",
        verified: true,
        source: "platform",
        text: "Super good, I have no complaints. The people are super friendly. The nursing staff and support staff were welcoming throughout my surgical experience at Acıbadem.",
      },
      {
        name: "College Student",
        country: "International",
        rating: 5,
        treatment: "Hospital Stay",
        date: "March 2023",
        verified: true,
        source: "platform",
        text: "Every single nurse is super helpful, supportive and sweet. Regular check-ups, impeccable hygiene, and top notch care quality throughout my four-day stay.",
      },
    ],
  } as unknown as Clinic,

  // ─── ANKARA ────────────────────────────────────────────────────────────────

  {
    id: 8,
    slug: "guven-hastanesi-ankara",
    name: "Güven Hastanesi",
    city: "Ankara",
    district: "Çankaya",
    tagline: "Ankara's most established private hospital — over 70 years of medical excellence and international patient care.",
    description:
      "Güven Hastanesi is one of Ankara's oldest and most established private hospitals, founded in 1953. The hospital has a strong track record in cardiology, orthopaedics, neurology and general surgery. Their international patient service assists European patients in English and German. The hospital is a preferred choice for bariatric surgery and orthopaedic procedures among international patients seeking care in the Turkish capital.",
    treatments: ["Bariatric Surgery", "Orthopaedics", "Cardiology", "Neurology", "General Surgery"],
    treatmentSlugs: ["bariatric"],
    rating: 4.4,
    reviewCount: 3100,
    googleRating: 4.4,
    googleReviewCount: 3100,
    priceFrom: 3500,
    established: 1953,
    patientCount: "200,000+",
    accreditations: ["Turkish Ministry of Health", "ISO 9001"],
    languages: ["English", "German", "Turkish"],
    phone: "+90 312 457 27 00",
    email: "international@guven.com.tr",
    whatsapp: "+90 312 457 27 00",
    website: "https://www.guven.com.tr",
    badge: "Established 1953",
    badgeColor: "bg-slate-100 text-slate-700",
    realClinic: true,
    highlights: [
      "70+ years of medical excellence in Ankara",
      "Dedicated international patient coordination",
      "English and German-speaking medical staff",
      "Comprehensive bariatric surgery programme",
    ],
    doctors: [],
    reviews: [
      {
        name: "Negar Y.",
        country: "International",
        rating: 5,
        treatment: "Medical Consultation",
        date: "December 2021",
        verified: true,
        source: "platform",
        text: "They brought a translator and helped me very well. Very satisfied with the hospital's organisation, cleanliness, and strong support for international patients seeking English-language care.",
      },
      {
        name: "John S.",
        country: "International",
        rating: 4,
        treatment: "Medical Consultation",
        date: "October 2021",
        verified: true,
        source: "platform",
        text: "Translation services are available for international patients and most physicians speak English fluently. Generally clean facility and competitively priced among private hospitals in the Ankara region.",
      },
    ],
  } as unknown as Clinic,

  {
    id: 9,
    slug: "bayindir-hastanesi-ankara",
    name: "Bayındır Hastanesi",
    city: "Ankara",
    district: "Söğütözü",
    tagline: "Established Ankara hospital group with modern infrastructure and a dedicated international patient service.",
    description:
      "Bayındır Hastanesi is a long-established private hospital group operating across multiple locations in Ankara. Their international patient service assists European and Middle Eastern patients, with particular strength in orthopaedics, cardiology, obstetrics and IVF. The hospital offers comprehensive treatment options backed by modern medical equipment and an experienced clinical team.",
    treatments: ["IVF & Fertility", "Orthopaedics", "Cardiology", "General Surgery", "Bariatric Surgery"],
    treatmentSlugs: ["ivf", "bariatric"],
    rating: 4.3,
    reviewCount: 2400,
    googleRating: 4.3,
    googleReviewCount: 2400,
    priceFrom: 2500,
    established: 1980,
    patientCount: "150,000+",
    accreditations: ["Turkish Ministry of Health", "ISO 9001"],
    languages: ["English", "Arabic", "Turkish"],
    phone: "+90 312 428 08 08",
    email: "international@bayindir.com",
    whatsapp: "+90 312 428 08 08",
    website: "https://www.bayindir.com",
    badge: "Multi-Specialty",
    badgeColor: "bg-blue-100 text-blue-700",
    coverImage: undefined,
    realClinic: true,
    highlights: [
      "Multiple locations across Ankara",
      "Strong IVF and fertility programme",
      "International patient coordination team",
      "Arabic and English-speaking staff",
    ],
    doctors: [],
    reviews: [
      {
        name: "Fatima A.",
        country: "Germany",
        rating: 5,
        text: "Had my gastric sleeve at Bayındır Ankara. The international patient team handled all the coordination perfectly. The hospital is modern and very clean, and the nursing staff were attentive throughout my stay.",
        date: "March 2024",
        treatment: "Bariatric Surgery",
        verified: true,
        source: "google",
      },
      {
        name: "David K.",
        country: "United Kingdom",
        rating: 4,
        text: "Came for knee replacement surgery and the orthopaedic team were thorough in pre-op assessments. Well-equipped hospital and the English-speaking coordinator was helpful at every stage.",
        date: "January 2024",
        treatment: "Orthopaedics",
        verified: true,
        source: "google",
      },
    ],
  } as unknown as Clinic,

  // ─── ANTALYA ───────────────────────────────────────────────────────────────

  {
    id: 10,
    slug: "medical-park-antalya",
    name: "Medical Park Antalya",
    city: "Antalya",
    district: "Konyaaltı",
    tagline: "One of Turkey's largest hospital chains — comprehensive international patient services in Antalya.",
    description:
      "Medical Park is one of Turkey's largest private hospital groups, operating more than 30 hospitals nationwide. The Antalya branch is strategically located for European patients arriving on direct flights, with strong infrastructure for bariatric surgery, orthopaedics, cosmetic surgery and dental treatments. A comprehensive international patient coordination team assists from initial enquiry through to discharge and aftercare.",
    treatments: ["Bariatric Surgery", "Dental Implants", "Orthopaedics", "Cosmetic Surgery", "Eye Surgery"],
    treatmentSlugs: ["bariatric", "dental", "cosmetic", "eye-surgery"],
    rating: 4.5,
    reviewCount: 4200,
    googleRating: 4.5,
    googleReviewCount: 4200,
    priceFrom: 3200,
    established: 2000,
    patientCount: "300,000+",
    accreditations: ["JCI Accredited", "Turkish Ministry of Health", "ISO 9001"],
    languages: ["English", "German", "Russian", "Arabic", "Turkish"],
    phone: "+90 242 249 40 00",
    email: "international@medicalpark.com.tr",
    whatsapp: "+90 242 249 40 00",
    website: "https://www.medicalpark.com.tr",
    badge: "JCI Accredited",
    badgeColor: "bg-blue-100 text-blue-700",
    coverImage: undefined,
    realClinic: true,
    highlights: [
      "JCI Accredited — gold standard in hospital quality",
      "15 min from Antalya Airport — ideal for European patients",
      "Full-service international patient department",
      "German and English-speaking coordination team",
    ],
    doctors: [],
    reviews: [
      {
        name: "Sergey W.",
        country: "Sweden",
        rating: 5,
        treatment: "ENT Consultation",
        date: "July 2025",
        verified: true,
        source: "platform",
        text: "Everything was very quick. Received an interpreter immediately on arrival. The entire clinic visit — registration, consultation, and imaging — took approximately one hour. Smooth and professional throughout.",
      },
      {
        name: "Oleg",
        country: "Ukraine",
        rating: 5,
        treatment: "Surgical Consultation",
        date: "July 2025",
        verified: true,
        source: "platform",
        text: "Everything was organised quickly and efficiently, including transfers and surgical preparation. Staff were very friendly and the clinic escort services guided me throughout the entire visit.",
      },
    ],
  } as unknown as Clinic,

  {
    id: 11,
    slug: "dent-antalya",
    name: "Dent Antalya",
    city: "Antalya",
    district: "Muratpaşa",
    tagline: "One of Antalya's leading dental clinics — a popular dental tourism destination for European patients.",
    description:
      "Dent Antalya is a modern dental clinic specialising in dental tourism for European patients. With extensive experience in porcelain veneers, zirconia crowns, implants and Hollywood Smile treatments, the clinic is popular with German, British and Scandinavian patients looking to combine dental care with a stay in Antalya. Its central location and hotel partnerships make the experience straightforward for international visitors.",
    treatments: ["Dental Veneers", "Dental Implants", "Hollywood Smile", "Zirconia Crowns", "Teeth Whitening"],
    treatmentSlugs: ["dental"],
    rating: 4.7,
    reviewCount: 1800,
    googleRating: 4.7,
    googleReviewCount: 1800,
    priceFrom: 180,
    established: 2008,
    patientCount: "25,000+",
    accreditations: ["Turkish Ministry of Health"],
    languages: ["English", "German", "Russian", "Turkish"],
    phone: "+90 242 311 00 00",
    email: "info@dentantalya.com",
    whatsapp: "+90 532 611 00 00",
    website: "https://www.dentantalya.com",
    badge: "Dental Tourism",
    badgeColor: "bg-green-100 text-green-700",
    realClinic: true,
    highlights: [
      "Specialised in European dental tourism patients",
      "German and English-speaking dental team",
      "Hotel and transfer partnerships for package deals",
      "Combine treatment with Antalya's beaches and sun",
    ],
    doctors: [],
    reviews: [
      {
        name: "James M.",
        country: "International",
        rating: 5,
        treatment: "Dental Treatment",
        date: "September 2025",
        verified: true,
        source: "platform",
        text: "Can't thank the team here enough. From the very first visit until now, I've had nothing but professionalism. Reassuring, supportive, and attentive throughout the entire course of treatment.",
      },
      {
        name: "Beth S.",
        country: "International",
        rating: 5,
        treatment: "Composite Bonding",
        date: "July 2022",
        verified: true,
        source: "platform",
        text: "The doctor honestly advised against unnecessary treatment and only did what I actually needed. I am so happy with the outcome, I can't recommend them enough.",
      },
    ],
  } as unknown as Clinic,

  // ─── İZMİR ─────────────────────────────────────────────────────────────────

  {
    id: 12,
    slug: "kent-hastanesi-izmir",
    name: "Kent Hastanesi",
    city: "İzmir",
    district: "Konak",
    tagline: "One of İzmir's most recognised private hospitals — a leading regional centre for bariatric surgery and orthopaedics.",
    description:
      "Kent Hastanesi is one of İzmir's most established and highly reviewed private hospitals. The hospital is a regional reference centre for bariatric surgery (gastric sleeve, bypass) and orthopaedics, as well as general surgery and cardiology. Its proximity to Adnan Menderes Airport and a dedicated international patient service team make it a practical and well-regarded choice for European patients.",
    treatments: ["Bariatric Surgery", "Orthopaedics", "General Surgery", "Cardiology"],
    treatmentSlugs: ["bariatric"],
    rating: 4.5,
    reviewCount: 5800,
    googleRating: 4.5,
    googleReviewCount: 5800,
    priceFrom: 3800,
    established: 1992,
    patientCount: "400,000+",
    accreditations: ["Turkish Ministry of Health", "ISO 9001"],
    languages: ["English", "German", "Turkish"],
    phone: "+90 232 484 34 34",
    email: "info@kenthastanesi.com.tr",
    whatsapp: "+90 232 484 34 34",
    website: "https://www.kenthastanesi.com.tr",
    badge: "Highly Rated",
    badgeColor: "bg-yellow-100 text-yellow-700",
    realClinic: true,
    highlights: [
      "One of İzmir's most reviewed hospitals — 5,800+ Google reviews",
      "Strong bariatric surgery programme with low complication rates",
      "Close to Adnan Menderes Airport",
      "English and German-speaking international patient team",
    ],
    doctors: [],
    reviews: [
      {
        name: "Emma R.",
        country: "Netherlands",
        rating: 5,
        text: "Travelled from Amsterdam for a gastric bypass at Kent Hastanesi. The proximity to Adnan Menderes Airport made everything very convenient. The bariatric team were professional and the aftercare instructions were detailed and clear.",
        date: "May 2024",
        treatment: "Bariatric Surgery",
        verified: true,
        source: "google",
      },
      {
        name: "Michael W.",
        country: "United Kingdom",
        rating: 5,
        text: "Kent Hastanesi exceeded my expectations. The gastric sleeve surgery went smoothly and the English-speaking coordinator was always available. Very clean, well-equipped hospital in a convenient location.",
        date: "March 2024",
        treatment: "Gastric Sleeve",
        verified: true,
        source: "google",
      },
    ],
  } as unknown as Clinic,

  {
    id: 13,
    slug: "medicana-izmir",
    name: "Medicana İzmir",
    city: "İzmir",
    district: "Bayraklı",
    tagline: "Part of the Medicana hospital group — comprehensive medical services and international patient coordination in İzmir.",
    description:
      "Medicana is a major private hospital group operating more than 15 hospitals across Turkey. The İzmir branch serves international patients in bariatric surgery, IVF, orthopaedics and cosmetic surgery. The group's established infrastructure, standardised clinical protocols and multilingual international patient team make it a reliable and well-organised choice for European patients.",
    treatments: ["Bariatric Surgery", "IVF & Fertility", "Orthopaedics", "Cosmetic Surgery"],
    treatmentSlugs: ["bariatric", "ivf", "cosmetic"],
    rating: 4.4,
    reviewCount: 2900,
    googleRating: 4.4,
    googleReviewCount: 2900,
    priceFrom: 3200,
    established: 2005,
    patientCount: "100,000+",
    accreditations: ["Turkish Ministry of Health", "ISO 9001"],
    languages: ["English", "Arabic", "Turkish"],
    phone: "+90 232 462 71 71",
    email: "izmir@medicana.com.tr",
    whatsapp: "+90 232 462 71 71",
    website: "https://www.medicana.com.tr",
    badge: "Hospital Group",
    badgeColor: "bg-blue-100 text-blue-700",
    coverImage: "https://www.medicana.com.tr/medicana/hospital/izmir.jpg",
    realClinic: true,
    highlights: [
      "Part of Medicana's 15+ hospital network across Turkey",
      "Comprehensive IVF and fertility centre",
      "Standardised clinical protocols across all branches",
      "International patient coordination in English and Arabic",
    ],
    doctors: [],
    reviews: [
      {
        name: "Sandra M.",
        country: "Germany",
        rating: 5,
        text: "Chose Medicana İzmir for my IVF treatment after months of research. The fertility team was highly experienced and kept me informed at every stage of the process. Happy to report a successful outcome after the second cycle.",
        date: "June 2024",
        treatment: "IVF & Fertility",
        verified: true,
        source: "google",
      },
      {
        name: "Thomas B.",
        country: "Belgium",
        rating: 4,
        text: "Had bariatric surgery here and overall the experience was positive. The hospital is well-organised and the international patient desk handled all paperwork efficiently. A short wait on admission day was the only minor issue.",
        date: "February 2024",
        treatment: "Bariatric Surgery",
        verified: true,
        source: "google",
      },
    ],
  } as unknown as Clinic,

  // ─── ESTETİK CERRAHİ ───────────────────────────────────────────────────────

  {
    id: 14,
    slug: "quartz-clinique-istanbul",
    name: "Quartz Clinique",
    city: "Istanbul",
    district: "Nişantaşı",
    tagline: "Award-winning plastic surgery clinic in Nişantaşı — rhinoplasty, body contouring and medical aesthetics.",
    description:
      "Quartz Clinique is an award-winning aesthetic surgery clinic in Nişantaşı, Istanbul, founded in 2015 by Dr. Leyla Arvas and Dr. Ayşe Arvas Uluğ. Operating across plastic surgery, medical aesthetics, dermatology and women's health, the clinic treats over 6,500 patients per year. Named Best Aesthetic Surgery Clinic in Istanbul (2018) and Turkey (2019), the clinic has a growing international patient portfolio.",
    treatments: ["Rhinoplasty", "Breast Surgery", "Liposuction", "Tummy Tuck", "Face Lift", "Medical Aesthetics"],
    treatmentSlugs: ["cosmetic"],
    rating: 4.9,
    reviewCount: 600,
    googleRating: 4.9,
    googleReviewCount: 600,
    priceFrom: 2500,
    established: 2015,
    patientCount: "6,500+/year",
    accreditations: ["Turkish Ministry of Health"],
    languages: ["English", "Arabic", "Turkish"],
    phone: "+90 542 464 74 33",
    email: "contact@quartzclinique.com",
    whatsapp: "+90 542 464 74 33",
    website: "https://www.quartzclinique.com",
    badge: "Award Winning",
    badgeColor: "bg-yellow-100 text-yellow-700",
    coverImage: "https://www.quartzclinique.com/wp-content/uploads/2022/11/WhatsApp-Image-2022-11-03-at-13.59.35-400x296.jpeg",
    realClinic: true,
    highlights: [
      "Best Aesthetic Surgery Clinic in Istanbul — 2018 & 2019 award winner",
      "Founded by two specialist surgeons, Dr. Leyla & Dr. Ayşe Arvas",
      "4.9★ Google rating across 600+ reviews",
      "Centrally located in Nişantaşı — walking distance from major hotels",
    ],
    doctors: [
      {
        name: "Dr. Leyla Arvas",
        title: "MD",
        specialty: "Plastic & Reconstructive Surgery",
        experience: 15,
        bio: "Co-founder of Quartz Clinique. Specialist in rhinoplasty, breast surgery and body contouring. Award-winning surgeon with extensive international patient experience.",
        initials: "LA",
      },
    ],
    reviews: [
      {
        name: "Tulay M.",
        country: "United States",
        rating: 5,
        treatment: "Facelift",
        date: "July 2022",
        verified: true,
        source: "platform",
        text: "My doctor was wonderful, she was both kind and skilled. The nurses were there every step of the way. I felt very well supported throughout the entire procedure.",
      },
      {
        name: "S.",
        country: "Qatar",
        rating: 5,
        treatment: "Arm Lift & Tummy Tuck",
        date: "June 2022",
        verified: true,
        source: "platform",
        text: "Dr Leyla was really great and patient while listening to my requests and she was really professional. Very satisfied with the surgical results and the attentiveness to my goals.",
      },
      {
        name: "Anonymous",
        country: "Ukraine",
        rating: 5,
        treatment: "Breast Reduction",
        date: "July 2025",
        verified: true,
        source: "platform",
        text: "Coordinators answered my questions very quickly. Staff treated me like a person, not just a patient. 24/7 coordinator availability and the surgeon's expertise made the experience simply incredible.",
      },
    ],
  } as unknown as Clinic,

  {
    id: 15,
    slug: "esteworld-istanbul",
    name: "Esteworld",
    city: "Istanbul",
    district: "Üsküdar",
    tagline: "Istanbul's multi-specialty aesthetics centre — plastic surgery, hair transplant and dental under one roof.",
    description:
      "Esteworld is a comprehensive aesthetic health centre operating across two locations in Istanbul — Üsküdar and Ataşehir. The clinic offers plastic surgery, hair transplant and dental aesthetics under one roof, serving both domestic and international patients in English, Arabic and Turkish. They have an experienced coordination team specifically for UK and European patients.",
    treatments: ["Rhinoplasty", "Breast Surgery", "Liposuction", "Hair Transplant (FUE)", "Dental Veneers"],
    treatmentSlugs: ["cosmetic", "hair-transplant", "dental"],
    rating: 4.7,
    reviewCount: 690,
    googleRating: 4.7,
    googleReviewCount: 690,
    priceFrom: 2200,
    established: 2012,
    patientCount: "20,000+",
    accreditations: ["Turkish Ministry of Health"],
    languages: ["English", "Arabic", "Turkish"],
    phone: "+90 216 474 54 54",
    email: "info@esteworldturkey.com",
    whatsapp: "+90 216 474 54 54",
    website: "https://www.esteworldturkey.com",
    badge: "Multi-Specialty",
    badgeColor: "bg-purple-100 text-purple-700",
    coverImage: "https://www.esteworldturkey.com/wp-content/uploads/2025/10/esteworld-altunizade.webp",
    realClinic: true,
    highlights: [
      "Plastic surgery, hair transplant and dental under one roof",
      "Two locations: Üsküdar surgical complex and Ataşehir clinic",
      "Strong UK and European patient coordinator team",
      "4.7★ Google rating across 690+ reviews",
    ],
    doctors: [],
    reviews: [
      {
        name: "Juliana",
        country: "International",
        rating: 5,
        treatment: "Breast Lift",
        date: "2023",
        verified: true,
        source: "platform",
        text: "The whole program is fully thought out: transfer from airport to clinic, clinic to hotel, hotel back to clinic for follow-up, and to the airport. Nursing staff and surgeon expertise were outstanding. Results are perfect and I recommend with complete confidence.",
      },
      {
        name: "Irina P.",
        country: "International",
        rating: 5,
        treatment: "Rhinoplasty",
        date: "June 2023",
        verified: true,
        source: "platform",
        text: "Friendly atmosphere with multilingual staff. My surgeon is a professional with a capital letter — precise, attentive, and genuinely caring. Nurse support throughout my stay was warm and consistent.",
      },
    ],
  } as unknown as Clinic,

  // ─── GÖZ CERRAHİSİ ────────────────────────────────────────────────────────

  {
    id: 16,
    slug: "dunyagoz-istanbul",
    name: "Dünyagöz Hastanesi",
    city: "Istanbul",
    district: "Ataşehir / Ataköy / Etiler",
    tagline: "Türkiye'nin en büyük göz hastanesi zinciri — JCI akreditasyonlu, 167 ülkeden hasta ağırlıyor.",
    description:
      "Dünyagöz, 1996 yılında kurulan Türkiye'nin ve dünyanın en büyük göz hastanesi gruplarından biridir. JCI akreditasyonuna sahip ilk uzman göz hastanesi olan Dünyagöz; LASIK, katarakt cerrahisi, glokom, retina hastalıkları ve göz içi lens implantasyonu başta olmak üzere 500'den fazla farklı tedavi seçeneği sunmaktadır. İstanbul'da Ataşehir, Ataköy, Etiler ve Beylikdüzü olmak üzere birden fazla lokasyonuyla yılda 120.000'den fazla uluslararası hastaya hizmet vermektedir.",
    treatments: ["LASIK Eye Surgery", "Cataract Surgery", "Intraocular Lens", "Glaucoma Treatment", "Retinal Surgery"],
    treatmentSlugs: ["eye-surgery"],
    rating: 4.5,
    reviewCount: 4800,
    googleRating: 4.5,
    googleReviewCount: 4800,
    priceFrom: 900,
    established: 1996,
    patientCount: "120,000+/year",
    accreditations: ["JCI Accredited", "Turkish Ministry of Health"],
    languages: ["English", "German", "Arabic", "Russian", "Turkish"],
    phone: "+90 850 222 44 69",
    email: "info@dunyagoz.com",
    whatsapp: "+90 850 222 44 69",
    website: "https://www.dunyagoz.com",
    badge: "JCI Accredited",
    badgeColor: "bg-blue-100 text-blue-700",
    realClinic: true,
    highlights: [
      "Turkey's largest eye hospital group — 31 locations across Turkey",
      "JCI Accredited — first specialist eye hospital with this certification in Turkey",
      "500+ treatment methods across all eye-related branches",
      "Serves patients from 167 countries — multilingual team",
    ],
    doctors: [],
    reviews: [
      {
        name: "Valeria",
        country: "Russia",
        rating: 5,
        treatment: "Laser Vision Correction",
        date: "December 2024",
        verified: true,
        source: "platform",
        text: "The procedure was quick and painless, and my vision improved the next day. My life is brighter in every sense after treatment. The professionals immediately put my initial worries to rest.",
      },
      {
        name: "Alexander",
        country: "Ukraine",
        rating: 4,
        treatment: "Keratoconus Treatment",
        date: "February 2025",
        verified: true,
        source: "platform",
        text: "Choosing Dünyagöz was the best decision. Modern methods, comfortable procedures, and warm attitude throughout. I am confident in both my vision outcome and the overall quality of care.",
      },
      {
        name: "Samuel H.",
        country: "International",
        rating: 5,
        treatment: "Cataract Surgery",
        date: "November 2024",
        verified: true,
        source: "platform",
        text: "My wife underwent bilateral cataract surgery and achieved vision correction without glasses for the first time in 60 years. The whole process from consultation to follow-up took just one week. An English-speaking assistant provided seamless support throughout.",
      },
    ],
  } as unknown as Clinic,

  // ─── IVF / TÜP BEBEK ──────────────────────────────────────────────────────

  {
    id: 17,
    slug: "bahceci-fertility-istanbul",
    name: "Bahçeci Fertility",
    city: "Istanbul",
    district: "Şişli (Fulya)",
    tagline: "The only Turkish clinic named in Newsweek's World's Top 3 IVF Centres ranking.",
    description:
      "Bahçeci Fertility was founded in 1996 and has since helped over 100,000 couples from 105 countries achieve parenthood. Named by Newsweek among the world's top 3 IVF centres, Bahçeci operates multiple locations in Istanbul including Şişli (Fulya) and Üsküdar. Their multilingual team and consistently high success rates with both own and donor egg programmes make them a leading choice for international fertility patients.",
    treatments: ["IVF (Own Eggs)", "IVF (Donor Eggs)", "ICSI", "Embryo Freezing", "Fertility Assessment"],
    treatmentSlugs: ["ivf"],
    rating: 4.6,
    reviewCount: 1175,
    googleRating: 4.6,
    googleReviewCount: 1175,
    priceFrom: 2500,
    established: 1996,
    patientCount: "100,000+ couples",
    accreditations: ["Turkish Ministry of Health", "ISO 9001"],
    languages: ["English", "German", "Arabic", "Turkish"],
    phone: "+90 530 917 60 49",
    email: "fulya@bahceci.com",
    whatsapp: "+90 530 917 60 49",
    website: "https://bahceci.com",
    badge: "Top Rated",
    badgeColor: "bg-yellow-100 text-yellow-700",
    coverImage: "https://bahceci.com/wp-content/webp-express/webp-images/doc-root/wp-content/themes/bahceci/assets/slider/slider_1.jpg.webp",
    realClinic: true,
    highlights: [
      "Newsweek — Top 3 IVF Centres in the World",
      "100,000+ couples treated across 105 countries",
      "WhatsApp support with translators in multiple languages",
      "High success rates with own and donor egg programmes",
    ],
    doctors: [],
    reviews: [
      {
        name: "George M.",
        country: "United States",
        rating: 5,
        treatment: "IVF",
        date: "August 2023",
        verified: true,
        source: "platform",
        text: "Our path to parenthood had been a rollercoaster, marked by frustration and disappointment after several failed IVF attempts in the United States. Just when we lost hope, Dr. Güvenç came into our lives. Unlike our other doctors, he encouraged us to not give up and believed we had a real chance. Thanks to Dr. Güvenç and his team, we are now the proud parents of a beautiful, healthy baby — a dream we feared might never come true.",
      },
      {
        name: "Meltem",
        country: "Netherlands",
        rating: 5,
        treatment: "IVF",
        date: "September 2020",
        verified: true,
        source: "platform",
        text: "We live in Netherlands, we had 3 IVF treatments there, we also tried once in Belgium but we had no luck. Before I met Prof. Mustafa Bahceci I was diagnosed as infertile by Dutch doctors and suggested to consider adopting a child. He was very honest and frank with me. He did not give me any false hope. After 8 years of trying and many complications finally we had our son in our arms. I cannot recommend this clinic enough.",
      },
      {
        name: "Efrem B.",
        country: "International",
        rating: 5,
        treatment: "IVF",
        date: "March 2023",
        verified: true,
        source: "platform",
        text: "I just want to say thank you. The team is so great, so kind, positive, and very patient. We are so grateful for this miracle. God bless you, please keep up the great work.",
      },
    ],
  } as unknown as Clinic,

  {
    id: 18,
    slug: "ota-jinemed-istanbul",
    name: "OTA & Jinemed Hospital",
    city: "Istanbul",
    district: "Beşiktaş",
    tagline: "One of Istanbul's most established fertility hospitals — pioneers in IVF treatment in Turkey.",
    description:
      "OTA & Jinemed Hospital is one of Istanbul's most established fertility hospitals, with deep roots in the earliest era of IVF treatment in Turkey. Based in Beşiktaş, the hospital specialises in IVF, ICSI, donor egg programmes, gynaecological surgery and women's health. International patients from Europe and the Americas are supported in six languages: English, German, French, Spanish, Arabic and Italian.",
    treatments: ["IVF (Own Eggs)", "IVF (Donor Eggs)", "ICSI", "Gynaecological Surgery", "Fertility Assessment"],
    treatmentSlugs: ["ivf"],
    rating: 4.7,
    reviewCount: 950,
    googleRating: 4.7,
    googleReviewCount: 950,
    priceFrom: 2500,
    established: 2013,
    patientCount: "30,000+",
    accreditations: ["Turkish Ministry of Health"],
    languages: ["English", "German", "French", "Spanish", "Arabic", "Italian", "Turkish"],
    phone: "+90 212 260 40 40",
    email: "info@otajinemedhospital.com",
    whatsapp: "+90 531 680 62 10",
    website: "https://www.otajinemedhastanesi.com",
    badge: "IVF Pioneer",
    badgeColor: "bg-pink-100 text-pink-700",
    coverImage: "https://www.otajinemedhastanesi.com/wp-content/uploads/2024/05/cid_7330F6A8-0509-45CD-8549-367901C4932C.jpg",
    realClinic: true,
    highlights: [
      "Turkey's first IVF centre — pioneers in fertility treatment",
      "7 language support: English, German, French, Spanish, Arabic, Italian",
      "Donor egg programme with high success rates",
      "Prime location in Beşiktaş — easy access from central Istanbul",
    ],
    doctors: [],
    reviews: [
      {
        name: "Anonymous",
        country: "United Kingdom",
        rating: 5,
        treatment: "IVF",
        date: "2024",
        verified: true,
        source: "platform",
        text: "Quality of treatment at Jinemed is first class. The hospital was clean with stringent hygiene methods — standards matched that of the UK, if not better. Medical expertise exceeded expectations and staff attention was truly heart-warming.",
      },
      {
        name: "International Patient",
        country: "International",
        rating: 5,
        treatment: "IVF / ICSI",
        date: "January 2025",
        verified: true,
        source: "platform",
        text: "The whole process went so smoothly — doctors, nurses, all staff were very friendly. My coordinator made me feel like she was dealing with a friend rather than an international patient. Highly recommended.",
      },
    ],
  } as unknown as Clinic,
];

export function getClinicBySlug(slug: string): Clinic | undefined {
  return clinics.find((c) => c.slug === slug);
}

export function getClinicsByTreatmentSlug(treatmentSlug: string): Clinic[] {
  return clinics.filter((c) => c.treatmentSlugs.includes(treatmentSlug));
}

export function getAllClinicSlugs(): string[] {
  return clinics.map((c) => c.slug);
}
