import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { GoogleAnalytics } from "@next/third-parties/google";
import { CurrencyProvider } from "@/components/ui/CurrencyProvider";

export const metadata: Metadata = {
  title: {
    default: "CliniqTurkey — Compare Verified Clinics & Save Up to 75%",
    template: "%s | CliniqTurkey",
  },
  description:
    "Compare verified clinics in Turkey for hair transplant, dental veneers, bariatric surgery, IVF and more. Real clinic ratings, transparent prices, direct clinic contact.",
  keywords: [
    "medical tourism turkey",
    "hair transplant turkey",
    "dental veneers turkey",
    "dental turkey",
    "bariatric surgery turkey",
    "gastric sleeve turkey",
    "IVF turkey",
    "compare clinics turkey",
    "istanbul clinics",
    "turkey medical tourism cost",
  ],
  metadataBase: new URL("https://www.cliniqturkey.com"),
  openGraph: {
    title: "CliniqTurkey — Compare Verified Clinics & Save Up to 75%",
    description:
      "Compare verified clinics in Turkey. Real clinic ratings, transparent prices, direct contact — no middleman.",
    type: "website",
    locale: "en_GB",
    siteName: "CliniqTurkey",
    // Social share image is generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "CliniqTurkey — Compare Verified Clinics & Save Up to 75%",
    description:
      "Compare verified clinics in Turkey. Real clinic ratings, transparent prices, direct contact.",
    // Twitter image is generated by src/app/twitter-image.tsx
  },
  alternates: {
    canonical: "https://www.cliniqturkey.com",
  },
  verification: {
    google: "GSHUh0pkcK4QVH6KkbPSHdHa5c94Kyy_phdJhRM1Kwg",
    other: {
      "p:domain_verify": "8fba9126a769b30d2e0fa015ece2203a",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <head>
        <meta name="google-site-verification" content="GSHUh0pkcK4QVH6KkbPSHdHa5c94Kyy_phdJhRM1Kwg" />
      </head>
      <body className="min-h-full flex flex-col antialiased">
        {/* Skip to main content — screen reader / keyboard users */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[9999] focus:px-4 focus:py-2 focus:bg-teal-600 focus:text-white focus:rounded-lg focus:font-semibold focus:text-sm"
        >
          Skip to main content
        </a>
        <ThemeProvider>
          <CurrencyProvider>{children}</CurrencyProvider>
        </ThemeProvider>
        <GoogleAnalytics gaId="G-L0B915Z4FQ" />
      </body>
    </html>
  );
}
